# Reference: https://kind.sigs.k8s.io/docs/user/configuration/

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: k8kreator.kind.local

networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  #apiServerPort: 6443

# Kubernetes API server runtime-config can be toggled using the runtimeConfig key,
# which maps to the --runtime-config kube-apiserver flag.
# This may be used to e.g. disable beta / alpha APIs.
runtimeConfig:
  "api/alpha": "false"

nodes:

- role: control-plane
  # https://hub.docker.com/r/kindest/node/tags
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  labels:
    k8kreator-target: k8kreator.kind.local

- role: worker
  # https://hub.docker.com/r/kindest/node/tags
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  labels:
    k8kreator-target: k8kreator.kind.local

- role: worker
  # https://hub.docker.com/r/kindest/node/tags
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  labels:
    k8kreator-target: k8kreator.kind.local

# End of file
