# Reference: https://kind.sigs.k8s.io/docs/user/configuration/

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: all.kind.local

nodes:

- role: control-plane
  # https://hub.docker.com/r/kindest/node/tags
  image: kindest/node:v1.28.0@sha256:9f3ff58f19dcf1a0611d11e8ac989fdb30a28f40f236f59f0bea31fb956ccf5c
  labels:
    cluster-target: all.kind.local
    cluster-role: master

- role: worker
  # https://hub.docker.com/r/kindest/node/tags
  image: kindest/node:v1.28.0@sha256:9f3ff58f19dcf1a0611d11e8ac989fdb30a28f40f236f59f0bea31fb956ccf5c
  labels:
    cluster-target: all.kind.local
    cluster-role: node

# End of file
