# Name:    jenkins
# Website: https://www.jenkins.io/
# Chart:   https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
# Values:  https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml

controller:

  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    # For Kubernetes v1.19+, use 'networking.k8s.io/v1'
    apiVersion: "extensions/v1"

  # This is required when TLS is not enabled
  jenkinsUrlProtocol: "http"

  # Don't use health probes in local
  healthProbes: false

  # Installs latest plugins as soon as Jenkins starts
  initializeOnce: true
  installLatestPlugins: true

  # Jenkins Configuration as Code
  JCasC:
    # Ignored if securityRealm is defined in controller.JCasC.configScripts
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    # Ignored if authorizationStrategy is defined in controller.JCasC.configScripts
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false

# Storage persistance configuration
persistence:
  enabled: false

# End of file
